apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: {{ .Values.namespace }}
  labels:
    app: devpulse-backend
spec:
  selector:
    app: devpulse-backend
  ports:
    - protocol: TCP
      port: {{ .Values.backend.servicePort }}
      targetPort: {{ .Values.backend.port }}
  type: ClusterIP