apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: {{ .Values.namespace  }}
  labels:
    app: postgres
type: Opaque
data:
  POSTGRES_USER: {{ .Values.secrets.dbUser | b64enc }}      # postgres
  POSTGRES_PASSWORD: {{ .Values.secrets.dbPassword | b64enc }}  # postgres
  POSTGRES_DB: {{ .Values.secrets.dbName | b64enc }}        # devpulse