import { useQuery } from '@tanstack/react-query'
import { Link, useParams } from 'react-router-dom'

import { getRetrospective } from '@/api/retrospectives'
import LLMStatusBar from '@/components/LLMStatusBar'
import MarkdownEditor from '@/components/MarkdownEditor'

export default function RetrospectivePage() {
  const params = useParams()
  const retroId = Number(params.retroId)

  const retroQuery = useQuery({
    queryKey: ['retro', retroId],
    queryFn: () => getRetrospective(retroId),
    enabled: Number.isFinite(retroId),
  })

  return (
    <div className="mx-auto max-w-5xl p-6">
      <div className="mb-6 flex items-center justify-between">
        <div>
          <h1 className="text-2xl font-semibold">Retrospective</h1>
          <p className="text-sm text-gray-600">Postmortem and runbook generated by Gemini.</p>
        </div>
        <Link className="rounded border border-gray-200 bg-white px-3 py-2 text-sm" to="/dashboard">
          Back
        </Link>
      </div>

      {retroQuery.isLoading ? (
        <div className="text-sm text-gray-600">Loading…</div>
      ) : retroQuery.isError ? (
        <div className="rounded bg-red-50 px-3 py-2 text-sm text-red-800">Failed to load retrospective.</div>
      ) : retroQuery.data ? (
        <div className="space-y-4">
          <LLMStatusBar state="done" tokenCount={retroQuery.data.tokens_used} />

          <div className="rounded border border-gray-200 bg-white p-4">
            <div className="text-sm text-gray-600">
              <div>
                <span className="font-medium">Model:</span> {retroQuery.data.model_used}
              </div>
              <div>
                <span className="font-medium">Severity score:</span> {retroQuery.data.severity_score}
              </div>
              <div>
                <span className="font-medium">MTTR (minutes):</span> {retroQuery.data.mttr_minutes}
              </div>
            </div>
          </div>

          <div className="grid grid-cols-1 gap-4 lg:grid-cols-2">
            <div>
              <div className="mb-2 text-sm font-medium">Postmortem</div>
              <MarkdownEditor value={retroQuery.data.postmortem_md} readOnly />
            </div>
            <div>
              <div className="mb-2 text-sm font-medium">Runbook</div>
              <MarkdownEditor value={retroQuery.data.runbook_md} readOnly />
            </div>
          </div>
        </div>
      ) : null}
    </div>
  )
}
