apiVersion: v1
kind: Service
metadata: 
  name: frontend-service
  namespace: devpulse
  labels:
    app: devpulse-frontend
spec:
  selector:
    app: devpulse-frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP