
name: DevPulse CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test-backend:
    name: Run Backend Tests
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      name: Checkout Code
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.11"
    - name: Install Dependencies
      working-directory: ./devpulse/backend
      run: |
        pip install -r requirements.txt

    - name: Run Tests
      working-directory: ./devpulse/backend
      run: |
        pytest tests/ -v
      env: 
        DATABASE_URL: sqlite+aiosqlite:///./test.db
        SYNC_DATABASE_URL: sqlite:///./test.db
        JWT_SECRET: test-secret-for-ci-only
        REDIS_URL: redis://localhost:6379/0
        LLM_PROVIDER: gemini
        GEMINI_API_KEY: fake-key-for-tests

  build-backend:
    name: Build Backend Image
    runs-on: ubuntu-latest
    needs: test-backend
    steps:
    - uses: actions/checkout@v4 
      name: Checkout Code

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v2


    - name: Build and Push Backend  Image
      env:
        ECR_REGISTRY: ${{ secrets.ECR_REGISTRY }}
        IMAGE_TAG: ${{ github.sha }}
      run: |
        docker build -t $ECR_REGISTRY/devpulse-backend:$IMAGE_TAG ./devpulse/backend
        docker tag $ECR_REGISTRY/devpulse-backend:$IMAGE_TAG $ECR_REGISTRY/devpulse-backend:latest
        docker push $ECR_REGISTRY/devpulse-backend:$IMAGE_TAG
        docker push $ECR_REGISTRY/devpulse-backend:latest
  
  build-frontend:
    name: Build Frontend Image
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      name: Checkout Code
    
    - name: Setup Node
      uses: actions/setup-node@v5
      with: 
        node-version: "20"
    
    - name : Install Dependencies
      working-directory: ./devpulse/frontend
      run: npm ci

    - name: Build Frontend
      working-directory: ./devpulse/frontend
      run: npm run build

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}
    
    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v2

    - name: Build Frontend and Push Image
      env: 
        ECR_REGISTRY: ${{ secrets.ECR_REGISTRY }}
        IMAGE_TAG: ${{ github.sha }}
      run: |
          docker build -t $ECR_REGISTRY/devpulse-frontend:$IMAGE_TAG ./devpulse/frontend
          docker tag $ECR_REGISTRY/devpulse-frontend:$IMAGE_TAG $ECR_REGISTRY/devpulse-frontend:latest
          docker push $ECR_REGISTRY/devpulse-frontend:latest
          docker push $ECR_REGISTRY/devpulse-frontend:$IMAGE_TAG

  deploy:
    name: Deploy to EKS
    runs-on: ubuntu-latest
    needs: [build-backend, build-frontend]
    if: github.ref == 'refs/heads/main'

    steps:
    - uses: actions/checkout@v4
      name: Checkout Code
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID_INFRA }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY_INFRA }}
        aws-region: ${{ secrets.AWS_REGION }}
    - name: Install kubectl
      run: |
        curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
        chmod +x kubectl
        mv kubectl /usr/local/bin/

    - name: Check if EKS cluster exists
      id: check-cluster
      run: |
        if aws eks describe-cluster \
            --name devpulse-cluster \
            --region ${{ secrets.AWS_REGION }} \
            --query 'cluster.status' 2>/dev/null; then
            echo "cluster_exists=true" >> $GITHUB_OUTPUT
          else
            echo "cluster_exists=false" >> $GITHUB_OUTPUT
          fi

    - name: Update kubeconfig
      if: steps.check-cluster.outputs.cluster_exists == 'true'
      run: |
        aws eks update-kubeconfig --name devpulse-cluster --region ${{ secrets.AWS_REGION }}
    
    - name: Apply k8s manifests
      if: steps.check-cluster.outputs.cluster_exists == 'true'
      run: |
        kubectl apply -f k8s/namespace.yaml
        kubectl apply -f k8s/postgres/
        kubectl apply -f k8s/redis/
        kubectl apply -f k8s/backend/
        kubectl apply -f k8s/worker/
        kubectl apply -f k8s/frontend/

    - name: Update the image tags
      if: steps.check-cluster.outputs.cluster_exists == 'true'
      env:
        ECR_REGISTRY: ${{ secrets.ECR_REGISTRY }}
        IMAGE_TAG: ${{ github.sha }}
      run: |
        kubectl set image deployment/devpulse-backend \
            devpulse-backend=$ECR_REGISTRY/devpulse-backend:$IMAGE_TAG \
            -n devpulse
        kubectl set image deployment/devpulse-worker \
            devpulse-worker=$ECR_REGISTRY/devpulse-backend:$IMAGE_TAG \
            -n devpulse
        kubectl set image deployment/devpulse-frontend \
            devpulse-frontend=$ECR_REGISTRY/devpulse-frontend:$IMAGE_TAG \
            -n devpulse

    - name: wait for rollout to complete
      if: steps.check-cluster.outputs.cluster_exists == 'true'
      run: |
        kubectl rollout status deployment/devpulse-backend -n devpulse --timeout=300s
        kubectl rollout status deployment/devpulse-worker -n devpulse   --timeout=300s
        kubectl rollout status deployment/devpulse-frontend -n devpulse --timeout=300s
    
    - name: Verify Pods are Running
      if: steps.check-cluster.outputs.cluster_exists == 'true'
      run: |
        kubectl get pods -n devpulse
        kubectl get services -n devpulse
      
    - name: Skip Deployment - no cluster
      if: steps.check-cluster.outputs.cluster_exists == 'false'
      run: |
        echo "EKS cluster does not exist. Skipping deployment."
        echo "Start cluster with eks-startup workflow first."

        