name: EKS Startup

on:
  workflow_dispatch:
    inputs:
      node_count:
        description: 'Number of nodes'
        required: true
        default: '2'
      node_type:
        description: 'EC2 instance type'
        required: true
        default: 't3.small'

jobs:
  create-cluster:
    name: Create EKS Cluster
    runs-on: ubuntu-latest

    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID_INFRA }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY_INFRA }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Install eksctl
        run: |
          curl --silent --location "https://github.com/weaveworks/eksctl/releases/latest/download/eksctl_$(uname -s)_amd64.tar.gz" | tar xz -C /tmp
          sudo mv /tmp/eksctl /usr/local/bin

      - name: Create EKS cluster
        run: |
          eksctl create cluster \
            --name devpulse-cluster \
            --region ${{ secrets.AWS_REGION }} \
            --nodes ${{ github.event.inputs.node_count }} \
            --node-type ${{ github.event.inputs.node_type }} \
            --managed

      - name: Install EBS CSI Driver
        run: |
          eksctl create addon \
            --name aws-ebs-csi-driver \
            --cluster devpulse-cluster \
            --region ${{ secrets.AWS_REGION }}

      - name: Install kubectl
        run: |
          curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
          chmod +x kubectl
          sudo mv kubectl /usr/local/bin/
          
      - name: Verify EBS CSI Addon
        run: |
          aws eks update-kubeconfig \
            --name devpulse-cluster \
            --region ${{ secrets.AWS_REGION }}

          kubectl get deployments -n kube-system
          kubectl get pods -n kube-system

          aws eks describe-addon \
            --cluster-name devpulse-cluster \
            --addon-name aws-ebs-csi-driver \
            --region ${{ secrets.AWS_REGION }}
          kubectl wait \
          --for=condition=Ready nodes \
          --all \
          --timeout=300s

          kubectl get nodes -o wide
