name: EKS Startup

on:
  workflow_dispatch:
    inputs:
      node_count:
        description: 'Number of nodes'
        required: true
        default: '2'
      node_type:
        description: 'EC2 instance type'
        required: true
        default: 't3.small'

jobs:
  create-cluster:
    name: Create EKS Cluster
    runs-on: ubuntu-latest

    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID_INFRA }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY_INFRA }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Install eksctl
        run: |
          curl --silent --location "https://github.com/weaveworks/eksctl/releases/latest/download/eksctl_$(uname -s)_amd64.tar.gz" | tar xz -C /tmp
          sudo mv /tmp/eksctl /usr/local/bin

      - name: Create EKS cluster
        run: |
          eksctl create cluster \
            --name devpulse-cluster \
            --region ${{ secrets.AWS_REGION }} \
            --nodes ${{ github.event.inputs.node_count }} \
            --node-type ${{ github.event.inputs.node_type }} \
            --managed

      - name: Install EBS CSI Driver
        run: |
          eksctl create addon \
            --name aws-ebs-csi-driver \
            --cluster devpulse-cluster \
            --region ${{ secrets.AWS_REGION }}

      - name: Install kubectl
        run: |
          curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
          chmod +x kubectl
          sudo mv kubectl /usr/local/bin/
          
      - name: Attach EBS CSI IAM Policy to Node Role
        run: |
          NODE_ROLE=$(aws iam list-roles \
            --query 'Roles[?contains(RoleName, `NodeInstanceRole`)].RoleName' \
            --output text)
          echo "Attaching policy to role: $NODE_ROLE"
          aws iam attach-role-policy \
            --role-name $NODE_ROLE \
            --policy-arn arn:aws:iam::aws:policy/service-role/AmazonEBSCSIDriverPolicy
           
          # Restart controller to pick up new permissions
          aws eks update-kubeconfig --name devpulse-cluster --region ${{ secrets.AWS_REGION }}
          kubectl rollout restart deployment/ebs-csi-controller -n kube-system    
      
      - name: Verify cluster
        run: |
          aws eks update-kubeconfig \
            --name devpulse-cluster \
            --region ${{ secrets.AWS_REGION }}
          kubectl get nodes